---
title: "Links"
toc: true
toc-title: "Contents"
---

## Academic Profiles

- [CESAER](https://cesaer.dijon.hub.inrae.fr/membres/personnel-scientifique/le-gallo-julie)
- [HAL](https://cv.hal.science/julie-le-gallo)
- [Google Scholar](https://scholar.google.fr/citations?user=cSCDeLEAAAAJ&hl=fr)
- [IDEAS / RePEc](https://ideas.repec.org/e/ple85.html)
- [ORCID](https://orcid.org/0000-0002-7296-2415)
- [ResearchGate](https://www.researchgate.net/profile/Julie_Le_Gallo)
- [ResearcherID](http://www.researcherid.com/rid/F-9167-2018)
- [ScholarGPS](https://scholargps.com/scholars/72269399096257/julie-le-gallo)

---

## Co-authors' Webpages

**A** — [Alonso Aguilar Ibarra](https://scholar.google.com.mx/citations?user=QmU_ovkAAAAJ&hl=es), [David Agrawal](http://www.uky.edu/~drag222/papers.html), [Yacine Allam](https://www2.dijon.inrae.fr/cesaer/membres/yacine-allam/), [Marius C.O. Amba](https://www.researchgate.net/profile/Marius-Amba), [Denis Anne](https://ideas.repec.org/f/pan380.html), [Luc Anselin](https://spatial.uchicago.edu/directory/luc-anselin-phd), [Giuseppe Arbia](https://search.usi.ch/en/people/989bc79a1a849fd8a70863d5967d0745/arbia-giuseppe), [Jean-Sauveur Ay](https://jsay.github.io/website/), [Kassoum Ayouba](https://ayoubakassoum.github.io/)

**B** — [Nazmiye Balta-Ozkan](https://www.cranfield.ac.uk/people/dr-nazmiye-ozkan-1347515), [Catherine Baumont](https://ledi.u-bourgogne.fr/membres-du-laboratoire/les-enseignants-chercheurs/34-pages-persos/371-baumont-catherine.html), [Steve Bazen](https://sites.google.com/site/stephenbazen/home), [Valentin Bellassen](https://www2.dijon.inrae.fr/cesaer/membres/valentin-bellassen/), [Saloua Benammou](https://www.semanticscholar.org/author/Saloua-Benammou/34581882), [Jaleleddine Ben Rejeb](https://scholar.google.com/citations?user=0IftROEAAAAJ&hl=fr), [Farès Ben Youssef](https://www.icmpd.org/file/download/59604/file/Fiche-Migrants%2520actuels.pdf), [Céline Boiteux-Orain](https://www.researchgate.net/scientific-contributions/11151949_Celine_BOITEUX-ORAIN), [Salima Bouayad-Agha](https://ideas.repec.org/f/pbo329.html), [Marie-Laure Breuillé](https://sites.google.com/site/breuillemarie/), [Anne Bretagnolle](https://www.pantheonsorbonne.fr/page-perso/abretagn), [Karine Brisset](https://crese.univ-fcomte.fr/fr/fiche-membre/48), [Thierry Brossard](https://www.researchgate.net/scientific-contributions/53881976_Brossard_Thierry)

**C** — [Diègo Cardenas-Morales](https://scholar.google.com/citations?user=ao9HAWwAAAAJ&hl=fr), [Jean Cavailhès](https://www2.dijon.inrae.fr/cesaer/membres/jean-cavailhès/), [Laëticia Challe](https://sites.google.com/site/laetitiachalle/), [Marie-Pier Champagne](https://scholar.google.com/citations?user=ZNl68eMAAAAJ&hl=fr), [Raja Chakir](https://sites.google.com/site/rajachakir/), [Capucine Chapel](https://capucine-chapel.netlify.app/), [Coro Chasco](https://corochasco.wordpress.com/), [François Cochard](https://crese.univ-fcomte.fr/en/fiche-membre/59)

**D** — [Yrabo Dabou](https://www.researchgate.net/profile/Yrabo-Dabou), [Sandy Dall'Erba](http://www.real.illinois.edu/faculty/dallerba.html), [Nicolas Debarsy](https://lem.univ-lille.fr/fileadmin/user_upload/laboratoires/lem/CV_Membres/2021CV_debarsy.pdf), [Laura Delmas](https://www.linkedin.com/in/laura-delmas-8b99b5179/), [Nicolas Devaux](https://www.uqar.ca/universite/a-propos-de-l-uqar/departements/departement-societes-territoires-et-developpement/devaux-nicolas), [François Des Rosiers](https://www.crad.ulaval.ca/membres/francois-des-rosiers), [Jean Dubé](https://www.esad.ulaval.ca/personnel/professeurs/jean-dube), [Marie-Line Duboz](https://crese.univ-fcomte.fr/fr/fiche-membre/27), [Loïc du Parquet](https://www.researchgate.net/profile/Loic_Du_Parquet), [Olivier Dupré](https://www.linkedin.com/in/olivier-dupr%C3%A9-168005171/)

**E** — [Cem Ertur](http://certur.free.fr/)

**F** — [Bernard Fingleton](https://www.landecon.cam.ac.uk/directory/professor-bernard-fingleton), [Alexandre Flage](https://sites.google.com/view/alexandre-flage-homepage/home), [Laurent Franckx](https://www.researchgate.net/profile/Laurent_Franckx2)

**G** — [Carl Gaigné](https://www6.rennes.inrae.fr/smart/Pages-Personnelles/Membres/Gaigne), [Federica Galli](https://www.unibo.it/sitoweb/federica.galli14/en), [Frédéric Gaschet](https://gretha.cnrs.fr/frederic-gaschet/), [Ghislain Geniaux](https://www.researchgate.net/profile/Ghislain_Geniaux), [Nikos Georgantzis](https://sites.google.com/view/nikolaosgeorgantzis/home), [Camille Grivault](https://www.researchgate.net/scientific-contributions/2009707179_Camille_Grivault), [Rachel Guillain](https://ledi.u-bourgogne.fr/m/toute-lactualite/actualites-externes/34-pages-persos/242-rachel-guillain.html), [Dong Guo](https://www.researchgate.net/profile/Dong_Guo3)

**H** — [Mohamed Hilal](https://www2.dijon.inrae.fr/cesaer/membres/mohamed-hilal/), [Sébastien Houde](https://sebastien-houde.com/)

**J** — [Hubert Jayet](https://pro.univ-lille.fr/hubert-jayet/)

**K** — [Yiannis Kamarianakis](https://sites.google.com/view/stat-learning-lab/people/research-personnel/yiannis-kamarianakis), [Eliakim Kakpo](https://www.kakpoeliakim.com/), [Philip Kostov](https://www.uclan.ac.uk/staff_profiles/dr_philip_kostov.php), [Mohamed Kriaa](https://www.researchgate.net/profile/Mohamed-Kriaa-2), [Nathalie Kroichvili](https://www.femto-st.fr/fr/personnel-femto/nathaliekroichvili)

**L** — [Rawaa Laajimi](https://www2.dijon.inrae.fr/cesaer/membres/laajimi-rawaa/), [Solène Larue](https://www.researchgate.net/profile/Solene_Larue), [Sophie Legras](https://sites.google.com/site/sophielegras/), [Diego Legros](https://www.researchgate.net/profile/Diego-Legros), [Renaud Le Goix](https://www.parisgeo.cnrs.fr/spip.php?article138), [Rémi Lei](https://www2.dijon.inrae.fr/cesaer/membres/remi-lei/), [James LeSage](https://faculty.txstate.edu/profile/520670), [Yannick L'Horty](http://www.erudite.univ-paris-est.fr/lequipe/enseignants-chercheurs/lhorty-yannick/), [Yuheng Ling](https://www.researchgate.net/profile/Yuheng-Ling), [Fernando Lopez](http://metodos.upct.es/falopez/)

**M** — [Estebania Martinez Jimenez](http://worldcat.org/identities/np-martinez%20jimenez,%20estebania%20teyeliz/), [Yoann Morin](https://yoannmorin.gitlab.io/), [Jan Mutl](https://www.ebs.edu/de/person/jan-mutl)

**N** — [Ingrid Nappi-Choulet](https://ingridnappichoulet.com/), [Claude Napoléone](https://www.researchgate.net/profile/Claude_Napoleone), [Youba Ndiaye](https://www2.dijon.inrae.fr/cesaer/membres/youba-ndiaye/)

**P** — [Antonio Paez](https://www.science.mcmaster.ca/geo/component/comprofiler/userprofile/paezha.html?Itemid=351), [Enrique Pérez-Campuzano](https://scholar.google.com/citations?user=OTzRdM0AAAAJ&hl=en), [Emmanuel Peterle](https://sites.google.com/site/peterleemmanuel/home), [Pascale Petit](http://www.erudite.univ-paris-est.fr/lequipe/enseignants-chercheurs/petit-pascale/), [Juan-Andrès Piedra-Peña](https://www.researchgate.net/profile/Juan-Piedra-Pena), [Alain Pirotte](https://www.u-paris2.fr/fr/universite/enseignants-chercheurs/m-alain-pirotte), [Maria Plotnikova](https://www.aber.ac.uk/en/abs/staff-profiles/listing/profile/map26/), [Anne Plunket](http://www.ritm.universite-paris-saclay.fr/researchers/anne-plunket/), [Gianfranco Piras](https://economics.catholic.edu/faculty-and-research/faculty-profiles/piras-gianfranco/index.html)

**R** — [Martin Regnaud](https://fr.linkedin.com/in/martin-regnaud-b1a9b1129), [Sergio J. Rey](http://sjrey.org/personal.html), [Didier Ruedin](https://druedin.com/)

**S** — [Legrand Saint-Cyr](https://www.researchgate.net/profile/Legrand-Saint-Cyr), [Bertrand Schmitt](https://www2.dijon.inrae.fr/cesaer/membres/bertrand-schmitt/), [Marc-Alexandre Sénégas](https://gretha.cnrs.fr/marc-alexandre-senegas/)

**T** — [Jean-Christian Tisserand](https://lessac.bsb-education.com/index.php?page=jean-christian-tisserand), [Isabelle Thomas](https://uclouvain.be/fr/repertoires/isabelle.thomas), [Olfa Toumi](https://www.researchgate.net/profile/Olfa_Toumi3)

**V** — [Andrès Vallone](http://www.eciem.cl/academico/3/ANDRS-VALLONE), [Lionel Védrine](https://lionelvedrine.wordpress.com/), [Javier Velázquez](https://www.researchgate.net/profile/Javier-Velazquez-2), [Alexandra Verlhiac](https://fr.linkedin.com/in/alexandra-verlhiac-819044153)

**W** — [Pierre Wavresky](https://www2.dijon.inrae.fr/cesaer/membres/pierre-wavresky/)

**Y** — [Oudah Yobom](https://www2.dijon.inrae.fr/cesaer/membres/oudah-yobom/), [Sonia Yousfi](https://www.researchgate.net/profile/Sonia-Yousfi)
